// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProjectBuilderExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "ProjectBuilderExtension.c2c2c13b-95fb-44f6-be0f-780445001d8f";
        public const string Name = "Project Builder Extension";
        public const string Description = @"Собирает проект в релиз и отправляет на указанный сервер";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Влад Шкурган";
        public const string Tags = "";
    }
}
